name:                hask-to-vhd
version:             0.1.0.0
github:              "githubuser/hask-to-vhd"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hask-to-vhd#readme>

dependencies:
- base >= 4.7 && < 5
- unique
- tasty >= 1.2 && < 2
- HUnit >= 1.6 && < 2
- unordered-containers >= 0.2 && < 0.3
- hashable >= 1.2 && < 2
- bytestring >= 0.10 && < 1
- text >= 1.2 && < 2
- split > 0.2 && < 1
- parsec > 3.1 && < 4
- mtl > 2.2 && < 3
- brick
- vty
- directory
- cursor >= 0.3 && < 1
- lens

library:
  source-dirs: src

executables:
  hask-to-vhd-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hask-to-vhd

tests:
  hask-to-vhd-test:
    main:                Spec.hs
#    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hask-to-vhd
